#!/bin/bash
# Any subsequent(*) commands which fail will cause the shell script to exit immediately
set -e

# Error

invalidUsage() {
  echo "⚠️  Invalid Usage: $0

  [-u = Username of remote machine]
  [-h = Hostname of remote machine]
  [-s = Source on local machine (Default: Current directory)]
  [-d = Destination on remote machine (Default: ~/Swish)]

  Usage: swish -s <source> -d <destination> -u <username> -h <hostname>"
  
  exit 1
}

# Parameters

while getopts ":u:h:s:d" o; do
    case "${o}" in
        u)
            user=${OPTARG}
            ;;
        h)
            host=${OPTARG}
            ;;
        s)
            source=${OPTARG}
            ;;
        d)
            destination=${OPTARG}
            ;;
        *)
            invalidUsage
            ;;
    esac
done
shift $((OPTIND-1))

# Check Parameters

if [ -z "${user}" ] || [ -z "${host}" ]; then
  invalidUsage
fi

if [ -z "${source}" ]; then
  source="."
fi

if [ -z "${destination}" ]; then
  destination="~/Swish"
fi

# Sync

echo "🚀  Start syncing project from ${source} to ${user}@${host}:${destination}"

rsync -azP --exclude=".build*" --exclude="Packages/*" --exclude="*.xcodeproj*" --exclude="*.DS_Store*" --exclude="swish" ${source} ${user}@${host}:${destination}

echo -e "💻  Did sync project to remote machine"

# Build

echo "⚒  Start building project"

ssh linux@linux-mate.local "source ~/.bash_profile; cd ~/Swish/${projectName}; swift build"

echo "✌️  Did build project on your remote machine"

# Finish
