#!/bin/bash
# Any subsequent(*) commands which fail will cause the shell script to exit immediately
set -e

# Error

invalidUsage() {
  echo "⚠️  Invalid Usage: $0

  [-u = Username of remote machine]
  [-h = Hostname of remote machine]
  [-d = Destination on remote machine (Default: ~/Swish)]

  Usage: swish -u <username> -h <hostname> -d <destination>"

  exit 1
}

# Parameters

while getopts ":u:h:d" o; do
    case "${o}" in
        u)
            user=${OPTARG}
            ;;
        h)
            host=${OPTARG}
            ;;
        d)
            destination=${OPTARG}
            ;;
        *)
            invalidUsage
            ;;
    esac
done
shift $((OPTIND-1))

# Check Parameters

if [ -z "${user}" ] || [ -z "${host}" ]; then
  invalidUsage
fi

if [ -z "${destination}" ]; then
  projectName=${PWD##*/}
  destination="~/Swish/${projectName}"
fi

# Sync

echo "🚀  Start syncing project to ${user}@${host}:${destination}"

rsync -azP --exclude=".build*" --exclude="Packages/*" --exclude="*.xcodeproj*" --exclude="*.DS_Store*" . ${user}@${host}:${destination}

echo -e "💻  Did sync project to remote machine"

# Build

echo "⚒  Start building project"

ssh linux@linux-mate.local "source ~/.bash_profile; cd ${destination}; swift build"

echo "✌️  Did build project on your remote machine"

# Finish
