#!/bin/bash
# ------------------------------------------------------------------
# [Author] Thomas Paul Mann
#          Build your Swift projects on a remote machine.
# ------------------------------------------------------------------

VERSION=1.2
USAGE="Usage: swish -d <destination> <username> <hostname>"

# --- Fail early ---------------------------------------------------

set -e

# --- Options processing -------------------------------------------

if [ $# == 0 ] ; then
    echo $USAGE
    exit 1;
fi

while getopts ":d:" optname
  do
    case "$optname" in
      d)
        destination=${OPTARG}
        ;;
      \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1;
        ;;
    esac
  done
shift $(($OPTIND - 1))

if [ -z "${destination}" ]; then
  projectName=${PWD##*/}
  destination="~/Swish/${projectName}"
fi

user=$1
host=$2

echo "-----------------------------"
echo "Configuration:"
echo "-----------------------------"
echo "Username: ${user}"
echo "Hostname: ${host}"
echo "Destination: ${destination}"
echo "-----------------------------"

# --- Body --------------------------------------------------------

# Sync

echo "🚀  Start syncing project to ${user}@${host}:${destination}"

rsync -azP --exclude=".build*" --exclude="Packages/*" --exclude="*.xcodeproj*" --exclude="*.DS_Store*" . ${user}@${host}:${destination}

echo -e "💻  Did sync project to remote machine"

# Build

echo "⚒  Start building project"

ssh ${user}@${host} "source ~/.bash_profile; cd ${destination}; swift build"

echo "✌️  Did build project on your remote machine"

# -----------------------------------------------------------------
